#! /bin/bash

set -e
set -u

bold=`tput smso`
offbold=`tput rmso`

if [ ! $# -eq 0 || $# -gt 4 ]
then echo "Usage: timer \<yyyy-mm-dd HH:MM\> [\<task\]>"
     exit 1
fi

clear

printf "\033[1m\t\t%s\n\t\t%s\033[0m\n\n" "ΑΝΤΙΜΕΤΡΗΣΙΣ" "============"


printf "\033[1m\tΛῆξις:\t\033[0m\t$1 $2 $3\n"
if [ $# -eq 4 ];then
	printf "\033[1m\tἜργον:\t\033[0m\t$4"
fi

deadline=$(date -j -f "%Y-%m-%d %a %H:%M" "$1 $2 $3" "+%s")
time=$(date "+%s")

pretty_print_time() {
	hours=$(($1 / 3600))
	mins=$((($1 % 3600)/60))
	secs=$((($1 % 3600)%60))
    printf "%d:%02d:%02d ὧρες" $hours $mins $secs
}


echo
while true; do
	diff=$(($deadline - $time))
	printf "\t\033[1mΧρόνος ἀπομένων:\033[0m ${bold} $(pretty_print_time $diff) ${offbold}\r"
	sleep 1 
	
	time=$(date "+%s")
done

printf "t\033[1mΧρόνος ἀπομένων:\033[0m ${bold} $(pretty_print_time 0) ${offbold}\n"

